In [ ]:
import numpy as np

**Procesamiento de un Neurona Artificial**

Crear el vector de entrada X

In [ ]:
X=np.array([[1.0],[-0.5],[2.5],[0.5]])
print(X)

[[ 1. ]
 [-0.5]
 [ 2.5]
 [ 0.5]]


Crear vector de pesos W

In [ ]:
W=np.array([[1.0],[-0.7],[-1.0],[0.5]])
print(W)

[[ 1. ]
 [-0.7]
 [-1. ]
 [ 0.5]]


Calculo de la neta

In [ ]:
Neta=(np.sum(np.multiply(X,W)))
print(Neta)

-0.8999999999999999


Function de activacion sigmoidal

In [ ]:
Y=1.0/(1+np.exp(-Neta))
print(Y)

0.28905049737499605


**Procesamiento de una capa de Neuronas**

W y B matricial, Wp(5x4), B(5x1) y X(4x1)

In [ ]:
Wp=np.array([[1.5,0.5, -0.5,1.0],[0.7,-0.8, 1.5,-1.0],[-1.0,1.2, 0.3,-0.7],[1.0,0.2,-0.3,0.3],[-0.2,0.8,-1.5,0.6]])
print(Wp)
B=np.array([[1.0],[-0.5],[1.5],[0.7],[0.8]])
print(B)
X=np.array([[1.0],[-0.5],[2.5],[0.5]])
print(X)

[[ 1.5  0.5 -0.5  1. ]
 [ 0.7 -0.8  1.5 -1. ]
 [-1.   1.2  0.3 -0.7]
 [ 1.   0.2 -0.3  0.3]
 [-0.2  0.8 -1.5  0.6]]
[[ 1. ]
 [-0.5]
 [ 1.5]
 [ 0.7]
 [ 0.8]]
[[ 1. ]
 [-0.5]
 [ 2.5]
 [ 0.5]]


Neta matricial

In [ ]:
Neta=((np.matmul(Wp,X))+B)
print(Neta)

[[ 1.5 ]
 [ 3.85]
 [ 0.3 ]
 [ 1.  ]
 [-3.25]]


Salida Matricial

In [ ]:
Y=1.0/(1+np.exp(-Neta))
print(Y)

[[0.81757448]
 [0.97916366]
 [0.57444252]
 [0.73105858]
 [0.03732689]]


**Procesamiento de una segunda capa de Neuronas**

W1 y B1 matricial, Wp1(3x5), B1(3x1) y Y(5x1)

In [ ]:
Wp1=np.array([[1.5,0.5, -0.5,-0.2,0.1],[0.7,-0.8, 1.5,-0.3,0.9],[-1.0,1.2, 0.3,-0.8,0.7]])
print(Wp1)
B1=np.array([[0.8],[-0.2],[-0.1]])
print(B1)
print(Y)

[[ 1.5  0.5 -0.5 -0.2  0.1]
 [ 0.7 -0.8  1.5 -0.3  0.9]
 [-1.   1.2  0.3 -0.8  0.7]]
[[ 0.8]
 [-0.2]
 [-0.1]]
[[0.81757448]
 [0.97916366]
 [0.57444252]
 [0.73105858]
 [0.03732689]]


Neta matricial

In [ ]:
Neta1=((np.matmul(Wp1,Y))+B1)
print(Neta1)

[[ 2.08624326]
 [ 0.26491161]
 [-0.12896338]]


Salida Matricial

In [ ]:
Y1=Neta1
print(Y1)

[[ 2.08624326]
 [ 0.26491161]
 [-0.12896338]]
