In [1]:
import numpy as np
import matplotlib.pyplot as plt 
import tensorflow as tf 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import datetime,os
from tensorboard.plugins.hparams import api as hp 

RED ADALINE

In [2]:
x_train=np.array([[0,0],[0,1],[1,0],[1,1]])
y_train=np.array([[0],[1],[1],[1]])
entrada_dimension=x_train.shape[1]
salida_dimension=y_train.shape[1]
print(x_train)
print(y_train)
print(entrada_dimension)
print(salida_dimension)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [1]
 [1]
 [1]]
2
1


In [5]:
def model_or():
  model=Sequential()
  model.add(Dense(1,input_dim=2,activation='relu'))

  model.summary()
  model.compile(loss='mean_squared_error',optimizer=tf.keras.optimizers.SGD(learning_rate=0.001))
  return model

Red multicapa en copuerta XOR

In [3]:
def model_or():
  model=Sequential()
  model.add(Dense(16,input_dim=2,activation='relu'))
  model.add(Dense(1,activation='sigmoid'))
  model.summary()
  model.compile(loss='mean_squared_error',optimizer=tf.keras.optimizers.SGD(learning_rate=0.01))
  return model

In [4]:
#Ejecución de función
modelo=model_or()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                48        
                                                                 
 dense_1 (Dense)             (None, 1)                 17        
                                                                 
Total params: 65
Trainable params: 65
Non-trainable params: 0
_________________________________________________________________


In [5]:
#Entrenamento para que tensoboard take data FORMA 1

log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(
    log_dir=log_dir,histogram_freq=1)
hparams_callback = hp.KerasCallback(log_dir,{
    'num_relu_units': 512,
    'dropout': 0.2
})


In [6]:
history1=modelo.fit(x_train,y_train,epochs=500 , batch_size=1,callbacks=[tensorboard_callback,hparams_callback])

Epoch 1/500
4/4 [==============================] - 0s 32ms/step - loss: 0.2738
Epoch 2/500
4/4 [==============================] - 0s 13ms/step - loss: 0.2695
Epoch 3/500
4/4 [==============================] - 0s 11ms/step - loss: 0.2654
Epoch 4/500
4/4 [==============================] - 0s 11ms/step - loss: 0.2613
Epoch 5/500
4/4 [==============================] - 0s 11ms/step - loss: 0.2574
Epoch 6/500
4/4 [==============================] - 0s 11ms/step - loss: 0.2536
Epoch 7/500
4/4 [==============================] - 0s 12ms/step - loss: 0.2499
Epoch 8/500
4/4 [==============================] - 0s 11ms/step - loss: 0.2462
Epoch 9/500
4/4 [==============================] - 0s 13ms/step - loss: 0.2427
Epoch 10/500
4/4 [==============================] - 0s 14ms/step - loss: 0.2393
Epoch 11/500
4/4 [==============================] - 0s 11ms/step - loss: 0.2360
Epoch 12/500
4/4 [==============================] - 0s 13ms/step - loss: 0.2327
Epoch 13/500
4/4 [==============================]

In [7]:
#Prediccion
prediccion_original=modelo.predict(x_train)
#prediccion_filtrada=(prediccion_original > 0.7) + 0
prediccion_filtrada=(prediccion_original > 0.7) + 0
print("Entradas: \n",x_train)
print("Respuesta de red: \n",prediccion_original)
print("Predicion hecha : \n",prediccion_filtrada)

1/1 [==============================] - 0s 386ms/step
Entradas: 
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Respuesta de red: 
 [[0.43828437]
 [0.8388255 ]
 [0.85762715]
 [0.9574479 ]]
Predicion hecha : 
 [[0]
 [1]
 [1]
 [1]]


In [ ]:
!tensorboard dev upload --logdir logs \
    --name "Red adaline OR mULTICAPA" \
    --description "(optional) Simple comparison of several hyperparameters"

2023-02-19 16:14:18.570268: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-02-19 16:14:18.570379: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-02-19 16:14:18.570397: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-02-19 16:14:20.165295: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to c